[general]
import = [
  "~/.config/alacritty/themes/themes/tokyo_night_storm.toml"
]

[window]
startup_mode = "SimpleFullscreen"
padding = { x = 9, y = 9 }

[terminal]
shell = { program = "/bin/zsh", args = ["-l", "-c", "zellij attach --index 0 --create"] }

[font]
normal = { family = "Hack Nerd Font Mono", style = "Regular" }
italic = { family = "Hack Nerd Font Mono", style = "Italic" }
bold = { family = "Hack Nerd Font Mono", style = "Bold" }
size = 16

[keyboard]
bindings = [
  { key = "Right", mods = "Command", chars = "\u001BF" },
  { key = "Left",  mods = "Command", chars = "\u001BB" },
]
